# Generated by Django 4.0 on 2021-12-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='favorites_user',
            new_name='user',
        ),
    ]
