# Generated by Django 4.0 on 2021-12-23 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_rating_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 23, 19, 16, 24, 828412)),
        ),
    ]
